<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Manager Home</title>
</head>
<body>
<%
	try {
			
			//Create a connection string
			String url = "jdbc:mysql://cs336project2017summer.cdbdnh5z4lat.us-west-2.rds.amazonaws.com:3306/cs336";
			//Load JDBC driver - the interface standardizing the connection procedure. Look at WEB-INF\lib for a mysql connector jar file, otherwise it fails.
			Class.forName("com.mysql.jdbc.Driver");

			//Create a connection to your DB
			Connection con = DriverManager.getConnection(url, "cs336", "cs336test");
					
			//Create a SQL statement
			Statement stmt = con.createStatement();

			// Check user id
			if(request.getSession().getAttribute("userid") != null){
				String id = (String) request.getSession().getAttribute("userid");
				//Make a SELECT query from the Employee table
				String str = "SELECT * FROM Emp_Manager M WHERE M.ID = '" + id +"'";
				//Run the query against the database.
				ResultSet result = stmt.executeQuery(str);
				//Check the result
				if (!result.next() ) {
					//Employee is a Customer Rep
					response.sendRedirect("CustomerRep.jsp");
					}
			}
			else {
				// send back to employee login page
				response.sendRedirect("EmployeeHome.jsp");
			}
			
			//close the connection.
			con.close();

		} catch (Exception e) {
			out.print("Problem with Database, please contact help desk. Sorry for the inconvenience.");
			request.getSession().setAttribute("userid", null);
		}
%>


Pick one of the Manager Actions below:
<br>
 <!-- Show html form to i) display something, ii) choose an action via a 
  | radio button -->
<form method="get" action="ManagerActions.jsp" enctype=text/plain>
    <!-- note the ManagerActions.jsp will be invoked when the choice is made -->
	<!-- The next lines give HTML for radio buttons being displayed -->
  <input type="radio" name="command" value="1"/> Add, Edit and Delete information for an employee/customer
  <br>
  <input type="radio" name="command" value="2"/> Obtain a sales report for a particular month
  <br>
  <input type="radio" name="command" value="3"/> Produce a comprehensive listing of all flights
  <br>
  <input type="radio" name="command" value="4"/> Produce a list of reservations by flight number or by customer name
  <br>
  <input type="radio" name="command" value="5"/> Produce a summary listing of revenue generated by a particular flight, destination city, or customer
  <br>
  <input type="radio" name="command" value="6"/> Determine which customer generated most total revenue
  <br>
  <input type="radio" name="command" value="7"/> Produce a list of most active flights
  <br>
  <input type="radio" name="command" value="8"/> Produce a list of all customers who have seats reserved on a given flight
  <br>
  <input type="radio" name="command" value="9"/> Produce a list of all flights for a given airport
  <br>
  <input type="radio" name="command" value="10"/> Produce a list of all flights whose arrival and departure times are on-time/delayed 
  <br>
  <input type="submit" value="submit" />
</form>
<br>
	


</body>
</html>